// TEMPORARY: sample data shaped exactly like the Django API answers.
// Edit freely (names, prices, stock). Delete this file when the real backend is connected.

export const CATEGORIES = [
  { id: 1, name: "Fruits & Vegetables", slug: "fruits-vegetables" },
  { id: 2, name: "Dairy & Eggs", slug: "dairy-eggs" },
  { id: 3, name: "Bakery", slug: "bakery" },
  { id: 4, name: "Snacks", slug: "snacks" },
  { id: 5, name: "Beverages", slug: "beverages" },
  { id: 6, name: "Household", slug: "household" },
  { id: 7, name: "Personal Care", slug: "personal-care" },
];

// [category id, name, image filename, price, unit, stock, description]
// Stock 0 shows "Out of stock"; a small stock shows a low number on the product page.
const ROWS = [
  [
    1,
    "Apple",
    "Apple.jpg",
    "1.50",
    "per lb",
    50,
    "Crisp, juicy apples with a balanced sweetness and a refreshing bite. Enjoy them on their own, slice them over cereal, or add them to salads and baked recipes. Store in the refrigerator to keep them fresh and firm.",
  ],
  [
    1,
    "Banana",
    "banana.jpg",
    "1.20",
    "per lb",
    60,
    "Naturally sweet bananas with a soft, creamy texture make an easy snack at home or on the go. Slice one into oatmeal, blend it into a smoothie, or use ripe bananas in baking. Keep at room temperature and refrigerate once fully ripe.",
  ],
  [
    1,
    "Orange",
    "Orange.jpg",
    "1.80",
    "per lb",
    45,
    "Bright, fragrant oranges have a juicy interior and a lively sweet-tart flavour. Peel one for a refreshing snack, or squeeze the fruit for fresh juice and use the zest to add citrus aroma to recipes. Refrigerate for longer-lasting freshness.",
  ],
  [
    1,
    "Strawberries",
    "Strawberries.jpg",
    "3.50",
    "1 pint",
    30,
    "These sweet, fragrant strawberries bring a fresh berry flavour to breakfasts, snacks, and desserts. Serve them whole, slice them over yogurt, or fold them into cakes and fruit salads. Keep refrigerated and rinse just before serving.",
  ],
  [
    1,
    "Grapes",
    "Grapes.jpg",
    "3.20",
    "per lb",
    28,
    "Crisp, juicy grapes offer a refreshing sweetness in every bite. Serve them chilled as a snack, add them to a cheese board, or halve them into salads for a burst of fruit. Store unwashed in the refrigerator and rinse before eating.",
  ],
  [
    1,
    "Watermelon",
    "Watermelon.jpg",
    "4.50",
    "each",
    0,
    "This refreshing watermelon has a juicy, lightly sweet flesh that is ideal for warm days and shared meals. Chill it before cutting, then serve the slices on their own or add cubes to a fruit salad. Refrigerate cut pieces in a covered container.",
  ],
  [
    1,
    "Tomato",
    "Tomato.jpg",
    "2.10",
    "per lb",
    40,
    "Ripe tomatoes bring a fresh, savoury sweetness and tender texture to everyday cooking. Slice them into sandwiches, chop them for salads, or simmer them into sauces and soups. Keep at room temperature until ripe, then refrigerate if needed.",
  ],
  [
    1,
    "Carrot",
    "carrot.jpg",
    "1.30",
    "per lb",
    55,
    "These crunchy carrots have a mild sweetness that works equally well raw or cooked. Enjoy them as a snack, grate them into salads, or roast them with your favourite seasonings for an easy side dish. Remove any leafy tops and refrigerate.",
  ],
  [
    1,
    "Potato",
    "Potato.jpg",
    "0.99",
    "per lb",
    80,
    "Versatile potatoes have a hearty texture that suits a wide range of meals. Boil or mash them, roast them until golden, or cut them into wedges for baking and frying. Store in a cool, dry place away from direct sunlight.",
  ],
  [
    1,
    "Broccoli",
    "broccoli.jpg",
    "2.40",
    "per head",
    25,
    "Fresh green broccoli has tender florets and a satisfying bite, making it an easy addition to everyday meals. Steam it gently, roast it for deeper flavour, or stir-fry it with vegetables and a sauce. Keep refrigerated and wash before cooking.",
  ],
  [
    1,
    "Cucumber",
    "cucumber.jpg",
    "0.90",
    "each",
    35,
    "Cool and crisp cucumber adds a refreshing crunch to simple meals. Slice it into salads and sandwiches, serve it with dips, or add it to chilled water for a light infusion. Keep refrigerated and rinse under cool water before use.",
  ],
  [
    1,
    "Onion",
    "onion.jpg",
    "1.10",
    "per lb",
    70,
    "Yellow onions develop a mellow sweetness as they cook and provide a savoury base for countless dishes. Dice them for soups and sauces, slice them for sandwiches, or roast them alongside vegetables. Store whole onions in a cool, dry, well-ventilated place.",
  ],
  [
    2,
    "Milk",
    "milk.jpg",
    "2.00",
    "1 L",
    40,
    "Fresh whole milk has a smooth, creamy taste for drinking and cooking. Pour it over cereal, add it to tea or coffee, or use it in sauces, baking, and everyday recipes. Keep refrigerated and return the container promptly after serving.",
  ],
  [
    2,
    "Eggs",
    "eggs.jpg",
    "2.50",
    "dozen",
    36,
    "A carton of farm eggs, ready for a dependable breakfast or a favourite recipe. Cook them scrambled, boiled, or fried, and use them to add structure and richness to baking. Keep refrigerated and handle carefully to protect the shells.",
  ],
  [
    2,
    "Cheddar Cheese",
    "Cheddar Cheese.jpg",
    "4.20",
    "200 g",
    22,
    "Mature cheddar has a firm texture and a rich, savoury flavour with a pleasantly sharp finish. Grate it over pasta, melt it into toasties, or serve slices with crackers and fruit. Keep chilled and wrap any unused portion to preserve its flavour.",
  ],
  [
    2,
    "Butter",
    "butter.jpg",
    "3.60",
    "250 g",
    30,
    "Creamy salted butter brings a rich finish to toast, vegetables, and home cooking. Spread it straight from the refrigerator or use it for baking, sautéing, and adding flavour to sauces. Keep chilled and reseal the wrapper after each use.",
  ],
  [
    2,
    "Plain Yogurt",
    "yogurt.jpg",
    "1.90",
    "500 g",
    26,
    "Thick, plain yogurt has a mild tang and a smooth, creamy texture. Enjoy it with fruit and granola, blend it into smoothies, or use it as a base for dips and dressings. Keep refrigerated and stir before serving if natural separation occurs.",
  ],
  [
    3,
    "Bread",
    "bread.jpg",
    "2.00",
    "loaf",
    0,
    "Soft sandwich bread has a tender crumb that is easy to slice and pair with sweet or savoury toppings. Make classic sandwiches, toast it for breakfast, or use it for croutons and bread pudding. Keep sealed to maintain freshness, or freeze slices for later.",
  ],
  [
    3,
    "Croissant",
    "Croissant.jpg",
    "1.40",
    "each",
    24,
    "This buttery croissant has a golden exterior and delicate, flaky layers. Enjoy it with coffee at breakfast, fill it with a savoury favourite, or warm it briefly before serving for a softer centre. Best enjoyed fresh on the day of purchase.",
  ],
  [
    3,
    "Bagels",
    "bagel.jpg",
    "3.00",
    "pack of 4",
    18,
    "Chewy bagels have a satisfying texture and make a versatile start to the day. Slice and toast them, then add cream cheese, eggs, or your preferred toppings for a quick meal. Keep sealed for freshness and freeze any bagels you will not use soon.",
  ],
  [
    4,
    "Potato Chips",
    "Potato Chips.jpg",
    "2.20",
    "150 g",
    45,
    "Lightly salted potato chips deliver a crisp crunch and familiar savoury flavour. Serve them alongside sandwiches, add them to a party snack spread, or enjoy a handful between meals. Close the package tightly after opening to help preserve their crunch.",
  ],
  [
    4,
    "Chocolate Bar",
    "Chocolate Bar.jpg",
    "1.60",
    "100 g",
    60,
    "Smooth milk chocolate offers a creamy, sweet treat that is easy to enjoy one piece at a time. Break off a square for an afternoon snack, share it with friends, or chop it into cookies and other baked goods. Store in a cool, dry place.",
  ],
  [
    4,
    "Cookies",
    "cookies.jpg",
    "2.80",
    "pack",
    38,
    "Chocolate chip cookies pair a golden edge with a soft, satisfying centre. Enjoy them with a glass of milk, pack one as an easy snack, or warm briefly for a fresh-from-the-oven feel. Keep the package sealed between servings to maintain their texture.",
  ],
  [
    4,
    "Popcorn",
    "Popcorn.jpg",
    "1.75",
    "100 g",
    33,
    "Ready-to-eat popcorn is light, crisp, and finished with a buttery flavour. It is an easy snack for a film night, a lunch break, or sharing with friends. Reseal the package after opening and store it somewhere cool and dry.",
  ],
  [
    4,
    "Mixed Nuts",
    "mixed nuts.jpg",
    "5.50",
    "250 g",
    3,
    "A savoury mix of roasted almonds, cashews, and peanuts brings several crunchy textures together in one convenient pack. Serve a small bowl with drinks, add a handful to a snack mix, or sprinkle them over salads. Store sealed in a cool, dry place.",
  ],
  [
    5,
    "Orange Juice",
    "orange juice.jpg",
    "3.30",
    "1 L",
    32,
    "This orange juice has a bright citrus taste and refreshing finish, making it a welcome choice at breakfast or any time of day. Serve it chilled on its own or use it in smoothies and fruit-based drinks. Refrigerate after opening and follow the package guidance.",
  ],
  [
    5,
    "Bottled Water",
    "botteled water.jpg",
    "0.80",
    "1.5 L",
    120,
    "Convenient bottled spring water is ready to take along to work, school, or a day out. Serve it chilled, keep a bottle nearby during meals, or use it to refill a reusable cup. Store unopened bottles in a cool place away from direct sunlight.",
  ],
  [
    5,
    "Green Tea",
    "Green Tea.jpg",
    "3.90",
    "20 bags",
    27,
    "These green tea bags brew a light, refreshing cup with a gentle tea flavour. Steep one in hot water for a few minutes, then enjoy it plain or with a slice of lemon. Store the box in a dry cupboard to keep the tea bags fresh.",
  ],
  [
    5,
    "Ground Coffee",
    "ground coffee.jpg",
    "6.50",
    "250 g",
    18,
    "Medium-roast ground coffee makes a balanced, aromatic brew for a relaxed morning or an afternoon break. Prepare it using your preferred filter or coffee maker, adjusting the strength to taste. Reseal the pack after opening and store it in a cool, dry place.",
  ],
  [
    5,
    "Cola",
    "cola.jpg",
    "1.50",
    "500 ml",
    70,
    "This chilled cola is a familiar, fizzy soft drink with a sweet, refreshing taste. Serve it cold on its own or alongside a meal, and pour over ice for extra chill. Refrigerate after opening and enjoy while freshly carbonated.",
  ],
  [
    6,
    "Dish Soap",
    "Dish Soap.jpg",
    "2.60",
    "500 ml",
    30,
    "This dish soap helps lift grease and food residue from plates, cookware, and utensils. Add a small amount to warm water or apply directly to a sponge, then rinse dishes thoroughly. Keep the bottle closed and stored safely away from children.",
  ],
  [
    6,
    "Paper Towels",
    "Paper Towels.jpg",
    "4.80",
    "2 rolls",
    25,
    "Strong, absorbent paper towels are handy for wiping kitchen surfaces and handling everyday spills. Tear off only what you need for quick clean-ups, drying produce, or lining a work area. Store the rolls in a clean, dry place until ready to use.",
  ],
  [
    6,
    "Laundry Detergent",
    "Laundry Detergent.jpg",
    "8.90",
    "2 L",
    15,
    "This laundry detergent is designed for everyday loads and works in cold-water washes. Measure the amount recommended on the label, add it according to your machine instructions, and wash clothing as usual. Keep the container closed and follow all package directions.",
  ],
  [
    7,
    "Toothpaste",
    "Toothpaste.jpg",
    "2.40",
    "100 ml",
    40,
    "Fluoride toothpaste is made for a clean, fresh-feeling start and finish to your day. Apply a small amount to a toothbrush and brush as directed on the package. Close the cap after use and store at room temperature.",
  ],
  [
    7,
    "Shampoo",
    "Shampoo.jpg",
    "4.50",
    "400 ml",
    28,
    "This gentle shampoo is suitable for everyday hair-washing routines and leaves hair feeling clean and refreshed. Massage a small amount into wet hair, then rinse thoroughly and repeat if desired. Avoid contact with eyes and follow the directions on the bottle.",
  ],
  [
    7,
    "Hand Soap",
    "Hand Soap.jpg",
    "1.90",
    "250 ml",
    35,
    "Moisturising liquid hand soap creates a gentle lather for everyday hand washing. Dispense a small amount onto wet hands, lather well, and rinse thoroughly with clean water. Keep the pump bottle closed when not in use and store it in a convenient place by the sink.",
  ],
];

export const PRODUCTS = ROWS.map(
  (
    [categoryId, name, imageFilename, price, unit, stock, description],
    index,
  ) => {
    const category = CATEGORIES.find((item) => item.id === categoryId);
    return {
      id: index + 1,
      name,
      description,
      price,
      unit,
      stock,
      image_url: `/products/${encodeURIComponent(imageFilename)}`,
      is_active: true,
      sold_count: (index * 7) % 23,
      category: category.id,
      category_name: category.name,
      category_slug: category.slug,
    };
  },
);
